version: '3.8'

services:

  # Cache Redis
  redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no
    container_name: voting-redis
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Base de données PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: voting-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 0s

  # Service Worker (.NET)
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    container_name: voting-worker
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - backend-network
    environment:
      REDIS_HOST: redis
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  # Application de Vote (Python)
  vote:
    build:
      context: ./vote
      dockerfile: Dockerfile
    container_name: voting-app
    ports:
      - "${VOTE_PORT}:80"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network
    environment:
      REDIS_HOST: redis
    restart: unless-stopped

  # Application de Résultats (Node.js)
  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    container_name: voting-result
    ports:
      - "${RESULT_PORT}:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  # Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: voting-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - frontend-network
    restart: unless-stopped

# Réseaux Docker
networks:
  frontend-network:
    driver: bridge
    name: voting-frontend
  backend-network:
    driver: bridge
    name: voting-backend

# Volumes persistants
volumes:
  db-data:
    driver: local
    name: voting-db-data
  jenkins-data:
    driver: local
    name: voting-jenkins-data

